## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Sat Jul 31 13:09:42 IST 2021
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
# Removed deprecated properties that will default to new values in AGP 10.0:
# - android.enableJetifier (now false by default, only enable if needed)
# - android.sdk.defaultTargetSdkToCompileSdkIfUnset (now true)
# - android.enableAppCompileTimeRClass (now true)
# - android.builtInKotlin (now true)
# - android.newDsl (now true)
# - android.r8.optimizedResourceShrinking (now true)
# - android.defaults.buildfeatures.resvalues (now false)
# - android.nonFinalResIds (now true)
android.nonTransitiveRClass=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false

# Performance improvement for large projects
android.dependency.excludeLibraryComponentsFromConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

android.builtInKotlin=false
android.newDsl=false
